title : EuroClack
production_url : http://clacktronics.github.io
url : http://clacktronics.github.io
permalink : none
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data","disable_indented_code_blocks"]
